[package]
name = "session-handler"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.0"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"